# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            JuMiverse
tagline:          'Blog site for the JuMiverse'
description:      'Blog site for the JuMiverse'
url:              

author:
  name:           'JuM'

paginate:         1

# Custom vars
version:          1.0.0

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}







  
