# Dependencies
theme: "minima"

pygments:        false

# Permalinks
permalink:        pretty

# Setup
title:            CURIEOSY
tagline:          'Blog site for curious people'
description:      'Blog site for the people'
url:              

author:
  name:           'hb'

paginate:         2
paginate_path: "/blog/page:num/"

# Custom vars
version:          1.0.0

# This is the list of pages to incldue in the header of the website.
pages_list:       {'Blog':'/blog','About':'/about/about','Categories':'/categories','Archive':'/archive'}







  
