# Dependencies
theme: "minima"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

pygments:        false

# Permalinks
permalink:        pretty

# Setup
title:            BRAINBODYHACKS
tagline:          'Der Blog für smarte Gehirnbenutzer'
description:      'Der Blog für smarte Gehirnbenutzer'
url:              www.brainbodyhacks.de

author:
  name:           'hb'

paginate:         2
paginate_path: "/blog/page:num/"

# Custom vars
version:          1.0.0

# This is the list of pages to incldue in the header of the website.
# pages_list:       {'Hacks':'/blog','Info':'/about/about','Kategorien':'/categories','FAQs':'/faqs'}







  
