# Dependencies
theme: "minima"

pygments:        false

# Permalinks
permalink:        pretty

# Setup
title:            FLOWINGBYTES
tagline:          'Blog site for flowing bytes of inspiration'
description:      'Blog site for a flowing bytes of inspiration'
url:              

author:
  name:           'hb'

paginate:         2
paginate_path: "/blog/page:num/"

# Custom vars
version:          1.0.0

# This is the list of pages to incldue in the header of the website.
pages_list:       {'Blog':'/blog','About':'/about/about','Categories':'/categories','Archive':'/archive'}







  
