name: ebook-pdf

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner

    - name: create file list
      id: files_list
      run: |
        # this will also include README.md
        echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT

    - uses: docker://pandoc/latex:2.9
      with:
        args: --output=ebook/output/ebook.pdf ebook/cover.svg ebook/title.txt ebook/de/01-introduction.md ebook/de/02-chapter2.md #${{ steps.files_list.outputs.files }}
   
                                              
    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "text-to-speach" --allow-empty)
        
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
